### ISSUE TITLE
How to undo notebook forget :)

### ISSUE THREAD

**Issue by srbiotik** [dvorka/mindforger-repository#12]
I know this is not exactly an issue, but it is a problem I did not know where to query about.

I accidentally forgot an important notebook, is there any way to restore it?

**Comment by MartinPetrei** [comment]
The notebook eliminated is on the `limbo` directory of the mindforger repository. Maybe you can move the file to the `memory` directory. Then re-read the repository.

**Comment by srbiotik** [comment]
Let me try...

**Comment by srbiotik** [comment]
Sweet it worked, thank you mister !
